sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Y3zclPcxGa4BCj1bqf0WmTnkY4xQw2yXWXmVnQsdb0/XlSx3APNJwBBfZdh/wwQ6NZuoLDDyhhyrhfa8qMw+Tmw4hJ9pePWncdR7oD6cEqa+oJEPQkpkFK2lY/cY+HBD/pTtyWxsCzrX3hE4T3E4FU0y1kaigeNuJzEKPF4lvQyBWQ+qtCUPfDBoVRV9M2TpAa8r7Mbl7PwlAFsIDlBm+14YvNQLQy4PTQ/aCtUetJpjbT3gPwzx8qVyITz9tmT+p7rKU4xFYFWwxyQWj35sOZ4vmpqOVcHt+EMYuI/YTlwHm2DRpKTYYE4BMtfctiSkekmqgUr50glksQ83GJFXrpaJf+yJStPNC39R4WJaB0t166fTTePVSR/wArdnPKS3Qef5bV1QssTTlxDRxPpxHY7HufTDE8fm9UKSDHClppaGAHhCuDgdmTWS5zmSS1lXKIHIhkrqESqzcNen21+C0w+MAGc/7EQA9bpGCBJzmeaJyz/bKJT/UFg9FF7jnUS3Egk9QRrls3rh+lbXGo8xj/fQj9jg1Dy/OxAWXt2A+GqTWurUZvRw1wqo0EHd9LEtTxBErBmg3XdaJ2ef0UDaN4fWtqbrMdItbSL5hIpRHoHvwX3PI/oRXeIvSTb71LUfDKDfQ/IkQzetugbXQGCardm9NO53w+Hf+fKQsKeUbIU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Dynamiter_647
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy